<img src="1748298529314.jpg" alt="My Profile Picture" width="200">

title: [Monday Obot]  
description: Data Analyst | SQL • Excel • Power BI • Python | Turning raw data into business insight
theme: jekyll-theme-cayman
